// Code generated by cmd/genlogo/main.go
// DO NOT EDIT

package logo

import _ "embed"

var (
	//go:embed svg/black-white-logo.svg
	blackWhiteLogoSVG []byte
	//go:embed svg/black-white-left.svg
	blackWhiteLeftSVG []byte
	//go:embed svg/black-white-middle.svg
	blackWhiteMiddleSVG []byte
	//go:embed svg/black-white-right.svg
	blackWhiteRightSVG []byte
	//go:embed svg/black-pink-logo.svg
	blackPinkLogoSVG []byte
	//go:embed svg/black-pink-left.svg
	blackPinkLeftSVG []byte
	//go:embed svg/black-pink-middle.svg
	blackPinkMiddleSVG []byte
	//go:embed svg/black-pink-right.svg
	blackPinkRightSVG []byte
	//go:embed svg/black-blue-logo.svg
	blackBlueLogoSVG []byte
	//go:embed svg/black-blue-left.svg
	blackBlueLeftSVG []byte
	//go:embed svg/black-blue-middle.svg
	blackBlueMiddleSVG []byte
	//go:embed svg/black-blue-right.svg
	blackBlueRightSVG []byte
	//go:embed svg/white-black-logo.svg
	whiteBlackLogoSVG []byte
	//go:embed svg/white-black-left.svg
	whiteBlackLeftSVG []byte
	//go:embed svg/white-black-middle.svg
	whiteBlackMiddleSVG []byte
	//go:embed svg/white-black-right.svg
	whiteBlackRightSVG []byte
	//go:embed svg/white-pink-logo.svg
	whitePinkLogoSVG []byte
	//go:embed svg/white-pink-left.svg
	whitePinkLeftSVG []byte
	//go:embed svg/white-pink-middle.svg
	whitePinkMiddleSVG []byte
	//go:embed svg/white-pink-right.svg
	whitePinkRightSVG []byte
	//go:embed svg/white-blue-logo.svg
	whiteBlueLogoSVG []byte
	//go:embed svg/white-blue-left.svg
	whiteBlueLeftSVG []byte
	//go:embed svg/white-blue-middle.svg
	whiteBlueMiddleSVG []byte
	//go:embed svg/white-blue-right.svg
	whiteBlueRightSVG []byte
	//go:embed png/black-white-logo-16.png
	blackWhiteLogoPNG16 []byte
	//go:embed png/black-white-logo-32.png
	blackWhiteLogoPNG32 []byte
	//go:embed png/black-white-logo-48.png
	blackWhiteLogoPNG48 []byte
	//go:embed png/black-white-logo-64.png
	blackWhiteLogoPNG64 []byte
	//go:embed png/black-white-logo-128.png
	blackWhiteLogoPNG128 []byte
	//go:embed png/black-white-logo-256.png
	blackWhiteLogoPNG256 []byte
	//go:embed png/black-white-logo-512.png
	blackWhiteLogoPNG512 []byte
	//go:embed png/black-white-left-16.png
	blackWhiteLeftPNG16 []byte
	//go:embed png/black-white-left-32.png
	blackWhiteLeftPNG32 []byte
	//go:embed png/black-white-left-48.png
	blackWhiteLeftPNG48 []byte
	//go:embed png/black-white-left-64.png
	blackWhiteLeftPNG64 []byte
	//go:embed png/black-white-left-128.png
	blackWhiteLeftPNG128 []byte
	//go:embed png/black-white-left-256.png
	blackWhiteLeftPNG256 []byte
	//go:embed png/black-white-left-512.png
	blackWhiteLeftPNG512 []byte
	//go:embed png/black-white-middle-16.png
	blackWhiteMiddlePNG16 []byte
	//go:embed png/black-white-middle-32.png
	blackWhiteMiddlePNG32 []byte
	//go:embed png/black-white-middle-48.png
	blackWhiteMiddlePNG48 []byte
	//go:embed png/black-white-middle-64.png
	blackWhiteMiddlePNG64 []byte
	//go:embed png/black-white-middle-128.png
	blackWhiteMiddlePNG128 []byte
	//go:embed png/black-white-middle-256.png
	blackWhiteMiddlePNG256 []byte
	//go:embed png/black-white-middle-512.png
	blackWhiteMiddlePNG512 []byte
	//go:embed png/black-white-right-16.png
	blackWhiteRightPNG16 []byte
	//go:embed png/black-white-right-32.png
	blackWhiteRightPNG32 []byte
	//go:embed png/black-white-right-48.png
	blackWhiteRightPNG48 []byte
	//go:embed png/black-white-right-64.png
	blackWhiteRightPNG64 []byte
	//go:embed png/black-white-right-128.png
	blackWhiteRightPNG128 []byte
	//go:embed png/black-white-right-256.png
	blackWhiteRightPNG256 []byte
	//go:embed png/black-white-right-512.png
	blackWhiteRightPNG512 []byte
	//go:embed png/black-pink-logo-16.png
	blackPinkLogoPNG16 []byte
	//go:embed png/black-pink-logo-32.png
	blackPinkLogoPNG32 []byte
	//go:embed png/black-pink-logo-48.png
	blackPinkLogoPNG48 []byte
	//go:embed png/black-pink-logo-64.png
	blackPinkLogoPNG64 []byte
	//go:embed png/black-pink-logo-128.png
	blackPinkLogoPNG128 []byte
	//go:embed png/black-pink-logo-256.png
	blackPinkLogoPNG256 []byte
	//go:embed png/black-pink-logo-512.png
	blackPinkLogoPNG512 []byte
	//go:embed png/black-pink-left-16.png
	blackPinkLeftPNG16 []byte
	//go:embed png/black-pink-left-32.png
	blackPinkLeftPNG32 []byte
	//go:embed png/black-pink-left-48.png
	blackPinkLeftPNG48 []byte
	//go:embed png/black-pink-left-64.png
	blackPinkLeftPNG64 []byte
	//go:embed png/black-pink-left-128.png
	blackPinkLeftPNG128 []byte
	//go:embed png/black-pink-left-256.png
	blackPinkLeftPNG256 []byte
	//go:embed png/black-pink-left-512.png
	blackPinkLeftPNG512 []byte
	//go:embed png/black-pink-middle-16.png
	blackPinkMiddlePNG16 []byte
	//go:embed png/black-pink-middle-32.png
	blackPinkMiddlePNG32 []byte
	//go:embed png/black-pink-middle-48.png
	blackPinkMiddlePNG48 []byte
	//go:embed png/black-pink-middle-64.png
	blackPinkMiddlePNG64 []byte
	//go:embed png/black-pink-middle-128.png
	blackPinkMiddlePNG128 []byte
	//go:embed png/black-pink-middle-256.png
	blackPinkMiddlePNG256 []byte
	//go:embed png/black-pink-middle-512.png
	blackPinkMiddlePNG512 []byte
	//go:embed png/black-pink-right-16.png
	blackPinkRightPNG16 []byte
	//go:embed png/black-pink-right-32.png
	blackPinkRightPNG32 []byte
	//go:embed png/black-pink-right-48.png
	blackPinkRightPNG48 []byte
	//go:embed png/black-pink-right-64.png
	blackPinkRightPNG64 []byte
	//go:embed png/black-pink-right-128.png
	blackPinkRightPNG128 []byte
	//go:embed png/black-pink-right-256.png
	blackPinkRightPNG256 []byte
	//go:embed png/black-pink-right-512.png
	blackPinkRightPNG512 []byte
	//go:embed png/black-blue-logo-16.png
	blackBlueLogoPNG16 []byte
	//go:embed png/black-blue-logo-32.png
	blackBlueLogoPNG32 []byte
	//go:embed png/black-blue-logo-48.png
	blackBlueLogoPNG48 []byte
	//go:embed png/black-blue-logo-64.png
	blackBlueLogoPNG64 []byte
	//go:embed png/black-blue-logo-128.png
	blackBlueLogoPNG128 []byte
	//go:embed png/black-blue-logo-256.png
	blackBlueLogoPNG256 []byte
	//go:embed png/black-blue-logo-512.png
	blackBlueLogoPNG512 []byte
	//go:embed png/black-blue-left-16.png
	blackBlueLeftPNG16 []byte
	//go:embed png/black-blue-left-32.png
	blackBlueLeftPNG32 []byte
	//go:embed png/black-blue-left-48.png
	blackBlueLeftPNG48 []byte
	//go:embed png/black-blue-left-64.png
	blackBlueLeftPNG64 []byte
	//go:embed png/black-blue-left-128.png
	blackBlueLeftPNG128 []byte
	//go:embed png/black-blue-left-256.png
	blackBlueLeftPNG256 []byte
	//go:embed png/black-blue-left-512.png
	blackBlueLeftPNG512 []byte
	//go:embed png/black-blue-middle-16.png
	blackBlueMiddlePNG16 []byte
	//go:embed png/black-blue-middle-32.png
	blackBlueMiddlePNG32 []byte
	//go:embed png/black-blue-middle-48.png
	blackBlueMiddlePNG48 []byte
	//go:embed png/black-blue-middle-64.png
	blackBlueMiddlePNG64 []byte
	//go:embed png/black-blue-middle-128.png
	blackBlueMiddlePNG128 []byte
	//go:embed png/black-blue-middle-256.png
	blackBlueMiddlePNG256 []byte
	//go:embed png/black-blue-middle-512.png
	blackBlueMiddlePNG512 []byte
	//go:embed png/black-blue-right-16.png
	blackBlueRightPNG16 []byte
	//go:embed png/black-blue-right-32.png
	blackBlueRightPNG32 []byte
	//go:embed png/black-blue-right-48.png
	blackBlueRightPNG48 []byte
	//go:embed png/black-blue-right-64.png
	blackBlueRightPNG64 []byte
	//go:embed png/black-blue-right-128.png
	blackBlueRightPNG128 []byte
	//go:embed png/black-blue-right-256.png
	blackBlueRightPNG256 []byte
	//go:embed png/black-blue-right-512.png
	blackBlueRightPNG512 []byte
	//go:embed png/white-black-logo-16.png
	whiteBlackLogoPNG16 []byte
	//go:embed png/white-black-logo-32.png
	whiteBlackLogoPNG32 []byte
	//go:embed png/white-black-logo-48.png
	whiteBlackLogoPNG48 []byte
	//go:embed png/white-black-logo-64.png
	whiteBlackLogoPNG64 []byte
	//go:embed png/white-black-logo-128.png
	whiteBlackLogoPNG128 []byte
	//go:embed png/white-black-logo-256.png
	whiteBlackLogoPNG256 []byte
	//go:embed png/white-black-logo-512.png
	whiteBlackLogoPNG512 []byte
	//go:embed png/white-black-left-16.png
	whiteBlackLeftPNG16 []byte
	//go:embed png/white-black-left-32.png
	whiteBlackLeftPNG32 []byte
	//go:embed png/white-black-left-48.png
	whiteBlackLeftPNG48 []byte
	//go:embed png/white-black-left-64.png
	whiteBlackLeftPNG64 []byte
	//go:embed png/white-black-left-128.png
	whiteBlackLeftPNG128 []byte
	//go:embed png/white-black-left-256.png
	whiteBlackLeftPNG256 []byte
	//go:embed png/white-black-left-512.png
	whiteBlackLeftPNG512 []byte
	//go:embed png/white-black-middle-16.png
	whiteBlackMiddlePNG16 []byte
	//go:embed png/white-black-middle-32.png
	whiteBlackMiddlePNG32 []byte
	//go:embed png/white-black-middle-48.png
	whiteBlackMiddlePNG48 []byte
	//go:embed png/white-black-middle-64.png
	whiteBlackMiddlePNG64 []byte
	//go:embed png/white-black-middle-128.png
	whiteBlackMiddlePNG128 []byte
	//go:embed png/white-black-middle-256.png
	whiteBlackMiddlePNG256 []byte
	//go:embed png/white-black-middle-512.png
	whiteBlackMiddlePNG512 []byte
	//go:embed png/white-black-right-16.png
	whiteBlackRightPNG16 []byte
	//go:embed png/white-black-right-32.png
	whiteBlackRightPNG32 []byte
	//go:embed png/white-black-right-48.png
	whiteBlackRightPNG48 []byte
	//go:embed png/white-black-right-64.png
	whiteBlackRightPNG64 []byte
	//go:embed png/white-black-right-128.png
	whiteBlackRightPNG128 []byte
	//go:embed png/white-black-right-256.png
	whiteBlackRightPNG256 []byte
	//go:embed png/white-black-right-512.png
	whiteBlackRightPNG512 []byte
	//go:embed png/white-pink-logo-16.png
	whitePinkLogoPNG16 []byte
	//go:embed png/white-pink-logo-32.png
	whitePinkLogoPNG32 []byte
	//go:embed png/white-pink-logo-48.png
	whitePinkLogoPNG48 []byte
	//go:embed png/white-pink-logo-64.png
	whitePinkLogoPNG64 []byte
	//go:embed png/white-pink-logo-128.png
	whitePinkLogoPNG128 []byte
	//go:embed png/white-pink-logo-256.png
	whitePinkLogoPNG256 []byte
	//go:embed png/white-pink-logo-512.png
	whitePinkLogoPNG512 []byte
	//go:embed png/white-pink-left-16.png
	whitePinkLeftPNG16 []byte
	//go:embed png/white-pink-left-32.png
	whitePinkLeftPNG32 []byte
	//go:embed png/white-pink-left-48.png
	whitePinkLeftPNG48 []byte
	//go:embed png/white-pink-left-64.png
	whitePinkLeftPNG64 []byte
	//go:embed png/white-pink-left-128.png
	whitePinkLeftPNG128 []byte
	//go:embed png/white-pink-left-256.png
	whitePinkLeftPNG256 []byte
	//go:embed png/white-pink-left-512.png
	whitePinkLeftPNG512 []byte
	//go:embed png/white-pink-middle-16.png
	whitePinkMiddlePNG16 []byte
	//go:embed png/white-pink-middle-32.png
	whitePinkMiddlePNG32 []byte
	//go:embed png/white-pink-middle-48.png
	whitePinkMiddlePNG48 []byte
	//go:embed png/white-pink-middle-64.png
	whitePinkMiddlePNG64 []byte
	//go:embed png/white-pink-middle-128.png
	whitePinkMiddlePNG128 []byte
	//go:embed png/white-pink-middle-256.png
	whitePinkMiddlePNG256 []byte
	//go:embed png/white-pink-middle-512.png
	whitePinkMiddlePNG512 []byte
	//go:embed png/white-pink-right-16.png
	whitePinkRightPNG16 []byte
	//go:embed png/white-pink-right-32.png
	whitePinkRightPNG32 []byte
	//go:embed png/white-pink-right-48.png
	whitePinkRightPNG48 []byte
	//go:embed png/white-pink-right-64.png
	whitePinkRightPNG64 []byte
	//go:embed png/white-pink-right-128.png
	whitePinkRightPNG128 []byte
	//go:embed png/white-pink-right-256.png
	whitePinkRightPNG256 []byte
	//go:embed png/white-pink-right-512.png
	whitePinkRightPNG512 []byte
	//go:embed png/white-blue-logo-16.png
	whiteBlueLogoPNG16 []byte
	//go:embed png/white-blue-logo-32.png
	whiteBlueLogoPNG32 []byte
	//go:embed png/white-blue-logo-48.png
	whiteBlueLogoPNG48 []byte
	//go:embed png/white-blue-logo-64.png
	whiteBlueLogoPNG64 []byte
	//go:embed png/white-blue-logo-128.png
	whiteBlueLogoPNG128 []byte
	//go:embed png/white-blue-logo-256.png
	whiteBlueLogoPNG256 []byte
	//go:embed png/white-blue-logo-512.png
	whiteBlueLogoPNG512 []byte
	//go:embed png/white-blue-left-16.png
	whiteBlueLeftPNG16 []byte
	//go:embed png/white-blue-left-32.png
	whiteBlueLeftPNG32 []byte
	//go:embed png/white-blue-left-48.png
	whiteBlueLeftPNG48 []byte
	//go:embed png/white-blue-left-64.png
	whiteBlueLeftPNG64 []byte
	//go:embed png/white-blue-left-128.png
	whiteBlueLeftPNG128 []byte
	//go:embed png/white-blue-left-256.png
	whiteBlueLeftPNG256 []byte
	//go:embed png/white-blue-left-512.png
	whiteBlueLeftPNG512 []byte
	//go:embed png/white-blue-middle-16.png
	whiteBlueMiddlePNG16 []byte
	//go:embed png/white-blue-middle-32.png
	whiteBlueMiddlePNG32 []byte
	//go:embed png/white-blue-middle-48.png
	whiteBlueMiddlePNG48 []byte
	//go:embed png/white-blue-middle-64.png
	whiteBlueMiddlePNG64 []byte
	//go:embed png/white-blue-middle-128.png
	whiteBlueMiddlePNG128 []byte
	//go:embed png/white-blue-middle-256.png
	whiteBlueMiddlePNG256 []byte
	//go:embed png/white-blue-middle-512.png
	whiteBlueMiddlePNG512 []byte
	//go:embed png/white-blue-right-16.png
	whiteBlueRightPNG16 []byte
	//go:embed png/white-blue-right-32.png
	whiteBlueRightPNG32 []byte
	//go:embed png/white-blue-right-48.png
	whiteBlueRightPNG48 []byte
	//go:embed png/white-blue-right-64.png
	whiteBlueRightPNG64 []byte
	//go:embed png/white-blue-right-128.png
	whiteBlueRightPNG128 []byte
	//go:embed png/white-blue-right-256.png
	whiteBlueRightPNG256 []byte
	//go:embed png/white-blue-right-512.png
	whiteBlueRightPNG512 []byte
	//go:embed ico/black-white-logo.ico
	blackWhiteLogoICO []byte
	//go:embed ico/black-white-left.ico
	blackWhiteLeftICO []byte
	//go:embed ico/black-white-middle.ico
	blackWhiteMiddleICO []byte
	//go:embed ico/black-white-right.ico
	blackWhiteRightICO []byte
	//go:embed ico/black-pink-logo.ico
	blackPinkLogoICO []byte
	//go:embed ico/black-pink-left.ico
	blackPinkLeftICO []byte
	//go:embed ico/black-pink-middle.ico
	blackPinkMiddleICO []byte
	//go:embed ico/black-pink-right.ico
	blackPinkRightICO []byte
	//go:embed ico/black-blue-logo.ico
	blackBlueLogoICO []byte
	//go:embed ico/black-blue-left.ico
	blackBlueLeftICO []byte
	//go:embed ico/black-blue-middle.ico
	blackBlueMiddleICO []byte
	//go:embed ico/black-blue-right.ico
	blackBlueRightICO []byte
	//go:embed ico/white-black-logo.ico
	whiteBlackLogoICO []byte
	//go:embed ico/white-black-left.ico
	whiteBlackLeftICO []byte
	//go:embed ico/white-black-middle.ico
	whiteBlackMiddleICO []byte
	//go:embed ico/white-black-right.ico
	whiteBlackRightICO []byte
	//go:embed ico/white-pink-logo.ico
	whitePinkLogoICO []byte
	//go:embed ico/white-pink-left.ico
	whitePinkLeftICO []byte
	//go:embed ico/white-pink-middle.ico
	whitePinkMiddleICO []byte
	//go:embed ico/white-pink-right.ico
	whitePinkRightICO []byte
	//go:embed ico/white-blue-logo.ico
	whiteBlueLogoICO []byte
	//go:embed ico/white-blue-left.ico
	whiteBlueLeftICO []byte
	//go:embed ico/white-blue-middle.ico
	whiteBlueMiddleICO []byte
	//go:embed ico/white-blue-right.ico
	whiteBlueRightICO []byte
)

type ResourceSet struct {
	Left   []byte
	Middle []byte
	Right  []byte
	Logo   []byte
}

type PNGResources struct {
	Size16  ResourceSet
	Size32  ResourceSet
	Size48  ResourceSet
	Size64  ResourceSet
	Size128 ResourceSet
	Size256 ResourceSet
	Size512 ResourceSet
}

type LogoResources struct {
	SVG ResourceSet
	PNG PNGResources
	ICO ResourceSet
}

var (
	LogoBlackWhite = LogoResources{
		SVG: ResourceSet{
			Logo:   blackWhiteLogoSVG,
			Left:   blackWhiteLeftSVG,
			Middle: blackWhiteMiddleSVG,
			Right:  blackWhiteRightSVG,
		},
		PNG: PNGResources{
			Size16: ResourceSet{
				Logo:   blackWhiteLogoPNG16,
				Left:   blackWhiteLeftPNG16,
				Middle: blackWhiteMiddlePNG16,
				Right:  blackWhiteRightPNG16,
			},
			Size32: ResourceSet{
				Logo:   blackWhiteLogoPNG32,
				Left:   blackWhiteLeftPNG32,
				Middle: blackWhiteMiddlePNG32,
				Right:  blackWhiteRightPNG32,
			},
			Size48: ResourceSet{
				Logo:   blackWhiteLogoPNG48,
				Left:   blackWhiteLeftPNG48,
				Middle: blackWhiteMiddlePNG48,
				Right:  blackWhiteRightPNG48,
			},
			Size64: ResourceSet{
				Logo:   blackWhiteLogoPNG64,
				Left:   blackWhiteLeftPNG64,
				Middle: blackWhiteMiddlePNG64,
				Right:  blackWhiteRightPNG64,
			},
			Size128: ResourceSet{
				Logo:   blackWhiteLogoPNG128,
				Left:   blackWhiteLeftPNG128,
				Middle: blackWhiteMiddlePNG128,
				Right:  blackWhiteRightPNG128,
			},
			Size256: ResourceSet{
				Logo:   blackWhiteLogoPNG256,
				Left:   blackWhiteLeftPNG256,
				Middle: blackWhiteMiddlePNG256,
				Right:  blackWhiteRightPNG256,
			},
			Size512: ResourceSet{
				Logo:   blackWhiteLogoPNG512,
				Left:   blackWhiteLeftPNG512,
				Middle: blackWhiteMiddlePNG512,
				Right:  blackWhiteRightPNG512,
			},
		},
		ICO: ResourceSet{
			Logo:   blackWhiteLogoICO,
			Left:   blackWhiteLeftICO,
			Middle: blackWhiteMiddleICO,
			Right:  blackWhiteRightICO,
		},
	}
	LogoBlackPink = LogoResources{
		SVG: ResourceSet{
			Logo:   blackPinkLogoSVG,
			Left:   blackPinkLeftSVG,
			Middle: blackPinkMiddleSVG,
			Right:  blackPinkRightSVG,
		},
		PNG: PNGResources{
			Size16: ResourceSet{
				Logo:   blackPinkLogoPNG16,
				Left:   blackPinkLeftPNG16,
				Middle: blackPinkMiddlePNG16,
				Right:  blackPinkRightPNG16,
			},
			Size32: ResourceSet{
				Logo:   blackPinkLogoPNG32,
				Left:   blackPinkLeftPNG32,
				Middle: blackPinkMiddlePNG32,
				Right:  blackPinkRightPNG32,
			},
			Size48: ResourceSet{
				Logo:   blackPinkLogoPNG48,
				Left:   blackPinkLeftPNG48,
				Middle: blackPinkMiddlePNG48,
				Right:  blackPinkRightPNG48,
			},
			Size64: ResourceSet{
				Logo:   blackPinkLogoPNG64,
				Left:   blackPinkLeftPNG64,
				Middle: blackPinkMiddlePNG64,
				Right:  blackPinkRightPNG64,
			},
			Size128: ResourceSet{
				Logo:   blackPinkLogoPNG128,
				Left:   blackPinkLeftPNG128,
				Middle: blackPinkMiddlePNG128,
				Right:  blackPinkRightPNG128,
			},
			Size256: ResourceSet{
				Logo:   blackPinkLogoPNG256,
				Left:   blackPinkLeftPNG256,
				Middle: blackPinkMiddlePNG256,
				Right:  blackPinkRightPNG256,
			},
			Size512: ResourceSet{
				Logo:   blackPinkLogoPNG512,
				Left:   blackPinkLeftPNG512,
				Middle: blackPinkMiddlePNG512,
				Right:  blackPinkRightPNG512,
			},
		},
		ICO: ResourceSet{
			Logo:   blackPinkLogoICO,
			Left:   blackPinkLeftICO,
			Middle: blackPinkMiddleICO,
			Right:  blackPinkRightICO,
		},
	}
	LogoBlackBlue = LogoResources{
		SVG: ResourceSet{
			Logo:   blackBlueLogoSVG,
			Left:   blackBlueLeftSVG,
			Middle: blackBlueMiddleSVG,
			Right:  blackBlueRightSVG,
		},
		PNG: PNGResources{
			Size16: ResourceSet{
				Logo:   blackBlueLogoPNG16,
				Left:   blackBlueLeftPNG16,
				Middle: blackBlueMiddlePNG16,
				Right:  blackBlueRightPNG16,
			},
			Size32: ResourceSet{
				Logo:   blackBlueLogoPNG32,
				Left:   blackBlueLeftPNG32,
				Middle: blackBlueMiddlePNG32,
				Right:  blackBlueRightPNG32,
			},
			Size48: ResourceSet{
				Logo:   blackBlueLogoPNG48,
				Left:   blackBlueLeftPNG48,
				Middle: blackBlueMiddlePNG48,
				Right:  blackBlueRightPNG48,
			},
			Size64: ResourceSet{
				Logo:   blackBlueLogoPNG64,
				Left:   blackBlueLeftPNG64,
				Middle: blackBlueMiddlePNG64,
				Right:  blackBlueRightPNG64,
			},
			Size128: ResourceSet{
				Logo:   blackBlueLogoPNG128,
				Left:   blackBlueLeftPNG128,
				Middle: blackBlueMiddlePNG128,
				Right:  blackBlueRightPNG128,
			},
			Size256: ResourceSet{
				Logo:   blackBlueLogoPNG256,
				Left:   blackBlueLeftPNG256,
				Middle: blackBlueMiddlePNG256,
				Right:  blackBlueRightPNG256,
			},
			Size512: ResourceSet{
				Logo:   blackBlueLogoPNG512,
				Left:   blackBlueLeftPNG512,
				Middle: blackBlueMiddlePNG512,
				Right:  blackBlueRightPNG512,
			},
		},
		ICO: ResourceSet{
			Logo:   blackBlueLogoICO,
			Left:   blackBlueLeftICO,
			Middle: blackBlueMiddleICO,
			Right:  blackBlueRightICO,
		},
	}
	LogoWhiteBlack = LogoResources{
		SVG: ResourceSet{
			Logo:   whiteBlackLogoSVG,
			Left:   whiteBlackLeftSVG,
			Middle: whiteBlackMiddleSVG,
			Right:  whiteBlackRightSVG,
		},
		PNG: PNGResources{
			Size16: ResourceSet{
				Logo:   whiteBlackLogoPNG16,
				Left:   whiteBlackLeftPNG16,
				Middle: whiteBlackMiddlePNG16,
				Right:  whiteBlackRightPNG16,
			},
			Size32: ResourceSet{
				Logo:   whiteBlackLogoPNG32,
				Left:   whiteBlackLeftPNG32,
				Middle: whiteBlackMiddlePNG32,
				Right:  whiteBlackRightPNG32,
			},
			Size48: ResourceSet{
				Logo:   whiteBlackLogoPNG48,
				Left:   whiteBlackLeftPNG48,
				Middle: whiteBlackMiddlePNG48,
				Right:  whiteBlackRightPNG48,
			},
			Size64: ResourceSet{
				Logo:   whiteBlackLogoPNG64,
				Left:   whiteBlackLeftPNG64,
				Middle: whiteBlackMiddlePNG64,
				Right:  whiteBlackRightPNG64,
			},
			Size128: ResourceSet{
				Logo:   whiteBlackLogoPNG128,
				Left:   whiteBlackLeftPNG128,
				Middle: whiteBlackMiddlePNG128,
				Right:  whiteBlackRightPNG128,
			},
			Size256: ResourceSet{
				Logo:   whiteBlackLogoPNG256,
				Left:   whiteBlackLeftPNG256,
				Middle: whiteBlackMiddlePNG256,
				Right:  whiteBlackRightPNG256,
			},
			Size512: ResourceSet{
				Logo:   whiteBlackLogoPNG512,
				Left:   whiteBlackLeftPNG512,
				Middle: whiteBlackMiddlePNG512,
				Right:  whiteBlackRightPNG512,
			},
		},
		ICO: ResourceSet{
			Logo:   whiteBlackLogoICO,
			Left:   whiteBlackLeftICO,
			Middle: whiteBlackMiddleICO,
			Right:  whiteBlackRightICO,
		},
	}
	LogoWhitePink = LogoResources{
		SVG: ResourceSet{
			Logo:   whitePinkLogoSVG,
			Left:   whitePinkLeftSVG,
			Middle: whitePinkMiddleSVG,
			Right:  whitePinkRightSVG,
		},
		PNG: PNGResources{
			Size16: ResourceSet{
				Logo:   whitePinkLogoPNG16,
				Left:   whitePinkLeftPNG16,
				Middle: whitePinkMiddlePNG16,
				Right:  whitePinkRightPNG16,
			},
			Size32: ResourceSet{
				Logo:   whitePinkLogoPNG32,
				Left:   whitePinkLeftPNG32,
				Middle: whitePinkMiddlePNG32,
				Right:  whitePinkRightPNG32,
			},
			Size48: ResourceSet{
				Logo:   whitePinkLogoPNG48,
				Left:   whitePinkLeftPNG48,
				Middle: whitePinkMiddlePNG48,
				Right:  whitePinkRightPNG48,
			},
			Size64: ResourceSet{
				Logo:   whitePinkLogoPNG64,
				Left:   whitePinkLeftPNG64,
				Middle: whitePinkMiddlePNG64,
				Right:  whitePinkRightPNG64,
			},
			Size128: ResourceSet{
				Logo:   whitePinkLogoPNG128,
				Left:   whitePinkLeftPNG128,
				Middle: whitePinkMiddlePNG128,
				Right:  whitePinkRightPNG128,
			},
			Size256: ResourceSet{
				Logo:   whitePinkLogoPNG256,
				Left:   whitePinkLeftPNG256,
				Middle: whitePinkMiddlePNG256,
				Right:  whitePinkRightPNG256,
			},
			Size512: ResourceSet{
				Logo:   whitePinkLogoPNG512,
				Left:   whitePinkLeftPNG512,
				Middle: whitePinkMiddlePNG512,
				Right:  whitePinkRightPNG512,
			},
		},
		ICO: ResourceSet{
			Logo:   whitePinkLogoICO,
			Left:   whitePinkLeftICO,
			Middle: whitePinkMiddleICO,
			Right:  whitePinkRightICO,
		},
	}
	LogoWhiteBlue = LogoResources{
		SVG: ResourceSet{
			Logo:   whiteBlueLogoSVG,
			Left:   whiteBlueLeftSVG,
			Middle: whiteBlueMiddleSVG,
			Right:  whiteBlueRightSVG,
		},
		PNG: PNGResources{
			Size16: ResourceSet{
				Logo:   whiteBlueLogoPNG16,
				Left:   whiteBlueLeftPNG16,
				Middle: whiteBlueMiddlePNG16,
				Right:  whiteBlueRightPNG16,
			},
			Size32: ResourceSet{
				Logo:   whiteBlueLogoPNG32,
				Left:   whiteBlueLeftPNG32,
				Middle: whiteBlueMiddlePNG32,
				Right:  whiteBlueRightPNG32,
			},
			Size48: ResourceSet{
				Logo:   whiteBlueLogoPNG48,
				Left:   whiteBlueLeftPNG48,
				Middle: whiteBlueMiddlePNG48,
				Right:  whiteBlueRightPNG48,
			},
			Size64: ResourceSet{
				Logo:   whiteBlueLogoPNG64,
				Left:   whiteBlueLeftPNG64,
				Middle: whiteBlueMiddlePNG64,
				Right:  whiteBlueRightPNG64,
			},
			Size128: ResourceSet{
				Logo:   whiteBlueLogoPNG128,
				Left:   whiteBlueLeftPNG128,
				Middle: whiteBlueMiddlePNG128,
				Right:  whiteBlueRightPNG128,
			},
			Size256: ResourceSet{
				Logo:   whiteBlueLogoPNG256,
				Left:   whiteBlueLeftPNG256,
				Middle: whiteBlueMiddlePNG256,
				Right:  whiteBlueRightPNG256,
			},
			Size512: ResourceSet{
				Logo:   whiteBlueLogoPNG512,
				Left:   whiteBlueLeftPNG512,
				Middle: whiteBlueMiddlePNG512,
				Right:  whiteBlueRightPNG512,
			},
		},
		ICO: ResourceSet{
			Logo:   whiteBlueLogoICO,
			Left:   whiteBlueLeftICO,
			Middle: whiteBlueMiddleICO,
			Right:  whiteBlueRightICO,
		},
	}
)
