# https://taskfile.dev

version: "3"

tasks:
  ci:
    desc: Run CI tasks
    cmds:
      - task: fmt
      - task: build
      - task: lint
      - task: test

  run:
    desc: Build and run the project
    deps:
      - build
    cmd: ./dist/tribar --debug

  build:
    desc: Build the project
    deps:
      - codegen
    cmd: go build -o ./dist/tribar ./cmd/tribar/main.go

  codegen:
    desc: Run all code generators of the project
    cmds:
      - task: gen:logo
      - task: gen:urpc

  # This task takes some seconds to run, so we use `sources` and `generates` to cache
  # it and avoid running it when it's not needed
  gen:logo:
    desc: Generate logo variants
    cmd: go run ./cmd/genlogo/main.go
    sources:
      - ./cmd/genlogo/**/*
    generates:
      - ./assets/logo/**/*

  # This code generator is high performance, we can run it every time without caching
  gen:urpc:
    desc: Generate UFO RPC code
    cmd: cd ./internal/server/api && urpc generate

  test:
    desc: Run all tests
    cmd: go test ./...

  lint:
    desc: Run all linters
    cmd: golangci-lint run

  fmt:
    desc: Format all code
    cmd: go fmt ./...
