# https://taskfile.dev

version: "3"

tasks:
  ci:
    desc: Run CI tasks
    cmds:
      - task: fmt
      - task: build
      - task: lint
      - task: test

  run:
    desc: Build and run the project
    deps:
      - build
    cmd: ./dist/tribar --debug

  build:
    desc: Build the project
    cmd: go build -o ./dist/tribar ./cmd/tribar/main.go

  gen:logo:
    desc: Generate logo variants
    cmd: go run ./cmd/genlogo/main.go

  test:
    desc: Run all tests
    cmd: go test ./...

  lint:
    desc: Run all linters
    cmd: golangci-lint run

  fmt:
    desc: Format all code
    cmd: go fmt ./...
