# https://taskfile.dev

version: '3'

tasks:
  ci:
    desc: Run CI tasks
    cmds:
      - task: fmt
      - task: build
      - task: lint
      - task: test

  run:
    desc: Build and run the project
    deps:
      - build
    cmd: ./dist/tribar --debug

  build:
    desc: Build the project
    deps:
      - codegen
    cmd: go build -o ./dist/tribar ./cmd/tribar/main.go

  codegen:
    desc: Run all code generators of the project
    cmds:
      - task: gen:logo
      - task: gen:urpc
      - task: gen:webapp

  # This task takes some seconds to run, so we use `sources` and `generates` to cache
  # it and avoid running it when it's not needed
  gen:logo:
    desc: Generate logo variants
    cmd: go run ./cmd/genlogo/main.go
    sources:
      - ./cmd/genlogo/**/*
    generates:
      - ./assets/logo/**/*

  # This code generator is high performance, we can run it every time without caching
  gen:urpc:
    desc: Generate UFO RPC code
    cmd: urpc generate ./schema/uforpc.toml

  # This task takes some seconds to run, so we use `sources` and `generates` to cache
  # it and avoid running it when it's not needed
  gen:webapp:
    desc: Build the webapp
    cmd: cd ./webapp && pnpm run build
    sources:
      - ./webapp/**/*
      - exclude: ./webapp/node_modules/**/*
      - exclude: ./webapp/.svelte-kit/**/*
      - exclude: ./webapp/build/**/*
    generates:
      - ./webapp/build/**/*

  test:
    desc: Run all tests
    cmd: go test ./...

  lint:
    desc: Run all linters
    cmds:
      - golangci-lint run
      - pnpm run lint
      - cd ./webapp && pnpm run check

  fmt:
    desc: Format all code
    cmds:
      - go fmt ./...
      - pnpm run fmt
